import assert from 'node:assert/strict'
import { mkdtempSync, rmSync, writeFileSync, readFileSync, renameSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { BridgeStore } from '../src/store.js'
import { resolveAtRestKeyFromEnv } from '../src/at-rest.js'
import type { ModulesSyncOp } from '../src/index.js'
import { canonicalContentOp } from '../src/content-access.js'
import { configureComposeAclStore, mutateComposeAclDocument, isComposeDocSharedWithMember, resetComposeAclStoreForTests } from '../src/compose-acl-store.js'
import { syncComposeContentAccess } from '../src/compose-content-access.js'

const root = mkdtempSync(join(tmpdir(), 'content-access-test-'))
let counter = 0
const op = (kind: string, targetId: string, rest: Partial<ModulesSyncOp> = {}): ModulesSyncOp => ({
  opId: `op-${++counter}`, kind, targetId, targetKind: kind.split('.')[0],
  originMemberId: 'admin', originRole: 'admin', originDevice: 'host',
  hlc: `${Date.now()}:0:host`, protocolVersion: 2, hopCount: 0, ...rest,
})
try {
  const deleteStore = new BridgeStore(join(root, 'delete-notice'), 21, null, null)
  for (const family of ['module', 'playbook', 'compose.doc']) {
    const created = op(`${family}.create`, family, { visibleToMemberIds: ['alice'] })
    const deleted = op(`${family}.delete`, family, { visibleToMemberIds: ['alice'] })
    deleteStore.appendOps([created, deleted])
    assert.equal(deleteStore.contentAccess.mayRead(created, 'alice', 'member'), false, 'deleted content stays denied')
    assert.equal(deleteStore.contentAccess.mayRead(deleted, 'alice', 'member'), true, 'former recipient must receive the deletion control')
    assert.equal(deleteStore.contentAccess.mayRead(deleted, 'outsider', 'member'), false)
    deleteStore.appendOp(op(`${family}.create`, family, { visibleToMemberIds: ['alice'] }))
    assert.equal(deleteStore.contentAccess.mayRead(deleted, 'alice', 'member'), false, 'old delete cannot destroy a restored item on catch-up')
  }
  let store = new BridgeStore(root, 21, null, null)
  const sha = 'a'.repeat(64)
  const shared = op('module.create', 'm', { visibleToMemberIds: ['alice', 'bob'] })
  const record = op('record.create', 'r', { moduleId: 'm', patch: { data: { image: { __teamspaceBlob: sha } } } })
  store.appendOps([shared, record])
  assert.equal(store.contentAccess.mayRead(record, 'alice', 'member'), true)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), true)
  const revokeNotice = op('module.share_revoked', 'm', { visibleToMemberIds: ['alice'], patch: { authoritativeDelete: true } })
  store.appendOp(revokeNotice)
  assert.equal(store.contentAccess.mayRead(record, 'alice', 'member'), false)
  assert.equal(store.contentAccess.mayReadRecord('r', 'alice', 'member'), false)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), false)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'bob', 'member'), true)
  assert.match(store.contentAccess.authorize(op('record.update', 'r'), 'alice', 'member')!, /revoked|parent/)
  store.appendOp(op('module.create', 'other', { visibleToMemberIds: ['alice'] }))
  assert.match(store.contentAccess.authorize(op('record.update', 'r', { moduleId: 'other' }), 'alice', 'member')!, /parent/)
  const borrowed = op('record.create', 'borrowed', { moduleId: 'other', patch: { image: { __teamspaceBlob: sha } } })
  assert.match(store.contentAccess.authorize(borrowed, 'alice', 'member')!, /Attachment/)
  const legacyBorrowed = { ...borrowed, patch: {}, payload_json: JSON.stringify(borrowed.patch) }
  assert.match(store.contentAccess.authorize(legacyBorrowed, 'alice', 'member')!, /Attachment/, 'legacy alternate content must receive the same blob authorization')
  const conflictingParent = { ...borrowed, patch: {}, payload_json: JSON.stringify({ moduleId: 'm', id: borrowed.targetId }) }
  assert.match(store.contentAccess.authorize(conflictingParent, 'alice', 'member')!, /parent/, 'validate the parent the desktop will actually apply')
  assert.match(store.contentAccess.authorize({ ...borrowed, patch: {}, module_id: 'm' } as ModulesSyncOp, 'alice', 'member')!, /parent/)
  assert.deepEqual(canonicalContentOp(legacyBorrowed).patch, borrowed.patch)
  assert.equal('payload_json' in canonicalContentOp(legacyBorrowed), false, 'wire must not retain a competing legacy override')
  store = new BridgeStore(root, 21, null, null)
  assert.equal(store.contentAccess.mayRead(record, 'alice', 'member'), false, 'restart cannot replay the old root grant over the checkpoint')
  store.appendOp(op('module.create', 'm', { visibleToMemberIds: ['alice', 'bob'] }))
  assert.equal(store.contentAccess.mayRead(revokeNotice, 'alice', 'member'), false, 're-granted recipients must not replay obsolete destructive revokes')
  const revision = store.contentAccess.revision(record)
  assert.equal(revision, 2)
  assert.match(store.contentAccess.authorize(op('record.update', 'r', { contentAclRevision: 0 }), 'alice', 'member')!, /revision/)
  assert.equal(store.contentAccess.authorize(op('record.update', 'r', { contentAclRevision: revision }), 'alice', 'member'), null)
  // A second legitimately shared reference keeps blob access after m is revoked.
  store.appendOp(op('record.create', 'shared-copy', { moduleId: 'other', patch: { image: { __teamspaceBlob: sha } } }))
  store.appendOp(op('module.share_revoked', 'm', { visibleToMemberIds: ['alice'] }))
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), true)
  writeFileSync(join(root, 'ops.jsonl'), '') // model retention removing all old snapshots
  store = new BridgeStore(root, 21, null, null)
  assert.equal(store.contentAccess.mayRead(record, 'alice', 'member'), false, 'grant tombstones survive ops retention')
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), true)
  writeFileSync(join(root, 'content-access.json'), '{broken')
  store = new BridgeStore(root, 21, null, null)
  assert.equal(store.contentAccess.healthy(), false)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'admin', 'admin'), false, 'corrupt authority fails closed, including Admin reads')
  assert.equal(await store.pruneOps(), 0, 'unreadable authority must keep every WAL row')

  const encryptedRoot = join(root, 'encrypted')
  const key = resolveAtRestKeyFromEnv({ TEAMSPACE_AT_REST_KEY: '1'.repeat(64) })
  assert.ok(key)
  store = new BridgeStore(encryptedRoot, 21, key, null)
  store.appendOps([shared, record])
  assert.equal(readFileSync(join(encryptedRoot, 'content-access.json'), 'utf8').includes('alice'), false)
  store = new BridgeStore(encryptedRoot, 21, key, null)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), true)
  const checkpoint = join(encryptedRoot, 'content-access.json')
  renameSync(checkpoint, `${checkpoint}.saved`)
  mkdirSync(checkpoint)
  assert.throws(() => store.appendOp(op('module.share_revoked', 'm', { visibleToMemberIds: ['alice'] })))
  assert.equal(store.contentAccess.healthy(), false, 'failed checkpoint freezes current access')
  assert.equal(await store.pruneOps(), 0, 'failed checkpoint cannot prune its write-ahead source')
  renameSync(checkpoint, `${checkpoint}.blocked-dir`)
  renameSync(`${checkpoint}.saved`, checkpoint)
  store = new BridgeStore(encryptedRoot, 21, key, null)
  assert.equal(store.contentAccess.healthy(), true)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), false, 'restart repairs the missing checkpoint event from the durable log')
  const composeRoot = join(root, 'compose-authority')
  store = new BridgeStore(composeRoot, 21, null, null)
  configureComposeAclStore(composeRoot)
  store.contentAccess.setComposeAccessCheck(isComposeDocSharedWithMember)
  assert.equal(mutateComposeAclDocument({ documentId: 'board', memberIds: ['alice', 'bob'] }).ok, true)
  syncComposeContentAccess(store)
  const board = op('compose.doc.create', 'board', { visibleToMemberIds: ['alice', 'bob'], patch: { image: { __teamspaceBlob: sha } } })
  store.appendOp(board)
  const beforeHttpCycle = store.contentAccess.revision(board)
  assert.equal(mutateComposeAclDocument({ documentId: 'board', memberIds: ['bob'] }).ok, true)
  assert.equal(store.contentAccess.mayRead(board, 'alice', 'member'), false, 'HTTP authority immediately denies snapshots before reconciliation')
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), false)
  // Model two committed HTTP changes before the ops checkpoint is repaired.
  assert.equal(mutateComposeAclDocument({ documentId: 'board', memberIds: ['alice', 'bob'] }).ok, true)
  store = new BridgeStore(composeRoot, 21, null, null)
  configureComposeAclStore(composeRoot)
  store.contentAccess.setComposeAccessCheck(isComposeDocSharedWithMember)
  assert.equal(syncComposeContentAccess(store).length, 1)
  assert.ok(store.contentAccess.revision(board) > beforeHttpCycle, 'same-audience HTTP cycle still invalidates stale work after restart')
  assert.match(store.contentAccess.authorize({ ...board, contentAclRevision: beforeHttpCycle }, 'alice', 'member')!, /revision/)
  assert.equal(store.contentAccess.authorize({ ...board, contentAclRevision: store.contentAccess.revision(board) }, 'alice', 'member'), null)
  assert.equal(syncComposeContentAccess(store).length, 0, 'reconciliation is idempotent')
  assert.equal(mutateComposeAclDocument({ documentId: 'board', remove: true }).ok, true)
  syncComposeContentAccess(store)
  writeFileSync(join(composeRoot, 'ops.jsonl'), '')
  store = new BridgeStore(composeRoot, 21, null, null)
  configureComposeAclStore(composeRoot)
  store.contentAccess.setComposeAccessCheck(isComposeDocSharedWithMember)
  syncComposeContentAccess(store)
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), false, 'HTTP removal tombstones survive both restart and log retention')
  assert.equal(mutateComposeAclDocument({ documentId: 'board', memberIds: null }).ok, true)
  syncComposeContentAccess(store)
  assert.equal(store.contentAccess.mayRead(board, 'alice', 'member'), true, 'explicit HTTP whole-team regrant replaces the removed scope')
  assert.match(store.contentAccess.authorize(op('compose.access', 'board'), 'admin', 'admin')!, /Server-only/)
  const aclFile = join(composeRoot, 'compose-live-acl.json')
  renameSync(aclFile, `${aclFile}.saved`)
  mkdirSync(aclFile)
  assert.equal(mutateComposeAclDocument({ documentId: 'board', remove: true }).ok, false)
  assert.equal(isComposeDocSharedWithMember('board', 'alice'), false, 'failed durable HTTP authority must not keep serving the old grant')
  assert.equal(store.contentAccess.mayReadBlob(sha, 'alice', 'member'), false)
  resetComposeAclStoreForTests()
  console.log('content access: current grants, parent binding, blob lineage, epochs, restart/retention, corruption and encryption passed')
} finally { rmSync(root, { recursive: true, force: true }) }
