import assert from 'node:assert/strict'
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,cpSync,readdirSync,symlinkSync,realpathSync} from 'node:fs'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {openIndependentAuthority,initializeCurrentAuthority} from '../src/independent-authority.js'
import {BridgeStore} from '../src/store.js'

const root=realpathSync(mkdtempSync(join(tmpdir(),'independent-authority-')))
try{
  const data=join(root,'data'),auth=join(root,'authority')
  assert.equal(openIndependentAuthority(data,auth),auth)
  assert.equal(openIndependentAuthority(data,auth),auth)
  assert.throws(()=>openIndependentAuthority(data,join(root,'missing')),/missing/,'even a server without records requires its retained authority')
  const foreignData=join(root,'foreign-data'),foreignAuth=join(root,'foreign-authority');openIndependentAuthority(foreignData,foreignAuth)
  assert.throws(()=>openIndependentAuthority(data,foreignAuth),/another server/)
  assert.throws(()=>openIndependentAuthority(data,join(data,'nested')),/outside/)
  assert.throws(()=>openIndependentAuthority(data,join(data,'..authority')),/outside/,'a dot-prefixed child is still inside the backup directory')
  const link=join(root,'link');symlinkSync(auth,link)
  assert.throws(()=>openIndependentAuthority(data,link),/real, independent/)
  const legacy=join(root,'legacy'),migrated=join(root,'migrated');mkdirSync(legacy)
  writeFileSync(join(legacy,'team.json'),'current team');writeFileSync(join(legacy,'members.json'),'current roster')
  mkdirSync(join(legacy,'chat'));writeFileSync(join(legacy,'chat','rooms.json'),'current private room members')
  writeFileSync(join(legacy,'ops.jsonl'),'record payload not an authorization file')
  mkdirSync(join(legacy,'record-tree'));writeFileSync(join(legacy,'record-tree','content-access.sqlite'),'current record authority')
  assert.throws(()=>openIndependentAuthority(legacy,migrated),/missing/)
  initializeCurrentAuthority(legacy,migrated)
  assert.equal(readFileSync(join(migrated,'members.json'),'utf8'),'current roster')
  assert.equal(readFileSync(join(legacy,'members.json'),'utf8'),'current roster','migration never consumes originals')
  assert.equal(readFileSync(join(migrated,'chat','rooms.json'),'utf8'),'current private room members')
  assert.ok(!readdirSync(migrated).includes('ops.jsonl'),'data payload is not conflated with retained authority')
  assert.equal(openIndependentAuthority(legacy,migrated),migrated)
  const old=join(root,'old');cpSync(legacy,old,{recursive:true});writeFileSync(join(migrated,'members.json'),'new roster after revocation')
  writeFileSync(join(old,'members.json'),'obsolete admin rights')
  assert.equal(openIndependentAuthority(old,migrated),migrated)
  assert.equal(readFileSync(join(migrated,'members.json'),'utf8'),'new roster after revocation')
  assert.throws(()=>initializeCurrentAuthority(old,migrated),/already/)
  rmSync(join(migrated,'team.json'))
  assert.throws(()=>openIndependentAuthority(old,migrated),/incomplete/)
  assert.equal(readFileSync(join(old,'members.json'),'utf8'),'obsolete admin rights','missing current identity never imports the old roster')
  const liveData=join(root,'live-data'),liveAuth=join(root,'live-authority')
  openIndependentAuthority(liveData,liveAuth)
  const live=new BridgeStore(liveData,21,null,null,undefined,liveAuth)
  const hello=live.helloOrBootstrap({memberId:'fresh-owner',deviceId:'fresh-device',displayName:'Owner'})
  assert.equal(hello.ok,true)
  assert.equal(JSON.parse(readFileSync(join(liveAuth,'.authorization-binding.json'),'utf8')).established,true)
  assert.equal(JSON.parse(readFileSync(join(liveAuth,'.authorization-binding.json'),'utf8')).checkpoints,1)
  const field=readFileSync(join(liveAuth,'team-field-acl.json')),fieldMarker=readFileSync(join(liveAuth,'team-field-acl.initialized'))
  rmSync(join(liveAuth,'team-field-acl.json'));rmSync(join(liveAuth,'team-field-acl.initialized'))
  assert.throws(()=>openIndependentAuthority(liveData,liveAuth),/incomplete/,'missing ACL plus its own marker cannot restore defaults from old operations')
  writeFileSync(join(liveAuth,'team-field-acl.json'),field);writeFileSync(join(liveAuth,'team-field-acl.initialized'),fieldMarker)
  assert.equal(openIndependentAuthority(liveData,liveAuth),liveAuth)
  writeFileSync(join(liveAuth,'members.json'),'[]')
  assert.throws(()=>new BridgeStore(liveData,21,null,null,undefined,liveAuth),/roster is empty/)
  writeFileSync(join(liveAuth,'team.json'),'not valid JSON')
  assert.throws(()=>new BridgeStore(liveData,21,null,null,undefined,liveAuth),/identity is unreadable/)
  assert.equal(readFileSync(join(liveAuth,'team.json'),'utf8'),'not valid JSON','corrupt identity is preserved for recovery')
  console.log('Independent authority: fresh/restart, empty-data missing volume, foreign volume, nested/symlink refusal, explicit migration, source preservation and data rollback passed')
}finally{rmSync(root,{recursive:true,force:true})}
